ci(github): update flow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,20 +1,43 @@
-name: main
+name: ci
 on:
   - push
   - pull_request
 
 jobs:
   build:
-    runs-on: ubuntu-latest
-
     strategy:
+      # Don't fast-fail on tag and master
+      fail-fast: ${{ github.event_name == 'pull_request' || (github.ref !=
+        'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')) }}
       matrix:
-        node-version:
-          - 12.x
+        config:
+          - os: ubuntu-latest
+            node-version: 12.x
+            kind: test
+          - os: macOS-latest
+            node-version: 12.x
+            kind: test
+          - os: windows-latest
+            node-version: 12.x
+            kind: test
+          #
+          - os: macOS-latest
+            node-version: 14.x
+            kind: test
+          - os: windows-latest
+            node-version: 14.x
+            kind: test
+          #
+          - os: ubuntu-latest
+            node-version: 14.x
+            kind: release
+
+    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
+    runs-on: ${{ matrix.config.os }}
 
     steps:
       - name: Set up Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v1
+        uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
 
@@ -26,6 +49,7 @@ jobs:
           #
           echo "Node $(node --version)"
           echo "Yarn $(yarn --version)"
+
       - uses: actions/checkout@v2
 
       - name: Cache Yarn packages
@@ -33,16 +57,9 @@ jobs:
         uses: actions/cache@v1
         with:
           path: ${{ steps.init.outputs.yarn_cache }}
-          key: ${{ runner.os }}-yarn_cache-${{ hashFiles('yarn.lock') }}
+          key: ${{ matrix.config.os }}-${{ matrix.config.kind }}-${{ hashFiles('yarn.lock') }}
           restore-keys: |
-            ${{ runner.os }}-yarn_cache-
-      - name: Cache node_modules
-        uses: actions/cache@v1
-        with:
-          path: node_modules
-          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ hashFiles('yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-${{ matrix.node-version }}-yarn-
+            ${{ matrix.config.os }}-${{ matrix.config.kind }}-
 
       - name: Installing
         run: yarn --frozen-lockfile --perfer-offline --link-duplicates
@@ -51,19 +68,22 @@ jobs:
         run: yarn lint
 
       - name: Unit tests
+        if: matrix.config.kind == 'release'
         run: yarn test --coverage --coverageReporters=lcov --coverageReporters=text-summary
 
       - name: Send test coverage to codecov
+        if: matrix.config.kind == 'release'
         continue-on-error: true
         uses: codecov/codecov-action@v1
 
       - name: Build
-        run: yarn build --outDir lib
+        run: yarn build
 
       - name: Archive lib components
+        if: matrix.config.kind == 'release'
         uses: actions/upload-artifact@v2
         with:
-          name: components
+          name: lib
           path: lib/
 
       - name: Functional tests
@@ -76,17 +96,17 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Set up Node
-        uses: actions/setup-node@v1
+        uses: actions/setup-node@v2
         with:
-          node-version: 12.x
+          node-version: 14.x
 
       - uses: actions/checkout@v2
 
       - name: Download lib form build job
         uses: actions/download-artifact@v2
         with:
-          name: components
-          path: .
+          name: lib
+          path: lib
 
       - name: Semantic Release
         uses: cycjimmy/semantic-release-action@v2
